package com.example.thanksd.MainPage

import com.example.thanksd.MainPage.dataclass.Quote

object QuotesData {
    val quotesList = listOf(
        Quote("When you have faults, do not fear to abandon them.", "Confucius"),
        Quote("They must often change who would be constant in happiness or wisdom. ", "Confucius"),
        Quote("Age is no guarantee of maturity.", "Lawana Blackwell"),
        Quote("Youth isn’t always all it’s touted to be. ", "Lawana Blackwell"),
        Quote("You will face many defeats in life, but never let yourself be defeated. ", "Maya Angelou"),
        Quote("The greatest glory in living lies not in never falling, but in rising every time we fall. ", "Nelson Mandela"),
        Quote("Life is either a daring adventure or nothing at all. ", "Helen Keller"),
        Quote("The goal of life is living in agreement with nature.", "Zeno"),
        Quote("This too shall pass. ", "Et hoc transibit"),
        Quote("The die is cast.", "Julius caesar"),
        Quote("Only I can change me life, no one can do it for me. ", "Carol Burnett"),
        Quote("When in doubt, choose change. ", "Lily leung"),
        Quote("Life is unfair, get used to it. ", "Bill Gates"),
        Quote("Being happy never goes out of style. ", "Lilly Pulitzer"),
        Quote("All you need in this life is ignorance and confidence, then success is sure. ", "Mark Twain"),
        Quote("Life is a mountain. Your goal is to find your path, not to reach the top", "Maxime Lagacé"),
        Quote("Life is from the inside out. When you shift on the inside, life shifts on the outside. ", "Kamal Ravikant"),
        Quote("Life can only be understood backwards; but it must be lived forwards. ", "Søren Kierkegaard"),
        Quote("Despite the forecast, live like it’s spring. ", "Lilly Pulitzer"),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", ""),
        Quote("", "")
    )
}