package com.example.thanksd.MainPage

import com.example.thanksd.MainPage.dataclass.Quote

object QuotesData {
    val quotesList = listOf(
        Quote("When you have faults, do not fear to abandon them.", "Confucius"),
        Quote("They must often change who would be constant in happiness or wisdom. ", "Confucius"),
        Quote("Age is no guarantee of maturity.", "Lawana Blackwell"),
        Quote("Youth isn’t always all it’s touted to be. ", "Lawana Blackwell"),
        Quote("You will face many defeats in life, but never let yourself be defeated. ", "Maya Angelou"),
        Quote("The greatest glory in living lies not in never falling, but in rising every time we fall. ", "Nelson Mandela"),
        Quote("Life is either a daring adventure or nothing at all. ", "Helen Keller"),
        Quote("The goal of life is living in agreement with nature.", "Zeno"),
        Quote("This too shall pass. ", "Et hoc transibit"),
        Quote("The die is cast.", "Julius caesar"),
        Quote("Only I can change me life, no one can do it for me. ", "Carol Burnett"),
        Quote("When in doubt, choose change. ", "Lily leung"),
        Quote("Life is unfair, get used to it. ", "Bill Gates"),
        Quote("Being happy never goes out of style. ", "Lilly Pulitzer"),
        Quote("All you need in this life is ignorance and confidence, then success is sure. ", "Mark Twain"),
        Quote("Life is a mountain. Your goal is to find your path, not to reach the top", "Maxime Lagacé"),
        Quote("Life is from the inside out. When you shift on the inside, life shifts on the outside. ", "Kamal Ravikant"),
        Quote("Life can only be understood backwards; but it must be lived forwards. ", "Søren Kierkegaard"),
        Quote("Despite the forecast, live like it’s spring. ", "Lilly Pulitzer"),
        Quote("The two most important days in your life are the day you are born and the day you find out why. ", "Mark Twain"),
        Quote("Nothing in more despicable than respect based on fear. ", "Albert camus"),
        Quote("Turn your wounds into wisdom. ", "Oprah Gail Winfrey"),
        Quote("Change the world by being yourself. ", "Amy Poehler"),
        Quote("Great minds have purposes, others have wishes. ", "Washington Irving"),
        Quote("Be gentle first with yourself. ", "Anonymous"),
        Quote("All we have is now. ", "Anonymous"),
        Quote("Believe in yourself. ", "Anonymous"),
        Quote("If you are not willing to risk the usual, you will have to settle for the ordinary. ", "Jim Rohn"),
        Quote("No great man ever complains of want of opportunity. ", "Anonymous"),
        Quote("A day without laughter is a day wasted. ", "Anonymous"),
        Quote("love what you have. ", "Anonymous"),
        Quote("It ain’t over till it’s over. ", "Anonymous"),
        Quote("No pain no gain. ", "Anonymous"),
        Quote("Rome is not built in a day. ", "Anonymous"),
        Quote("Never lose sight of the face that the most important yard stick to your success is how you treat other people. ", "Barbara Bush"),
        Quote("Success is not final; failure is not fatal: It is the courage to continue that counts. ", "Winston S. Churchill"),
        Quote("Success usually comes to those who are too busy to be looking for it.", "Henry David Thoreau"),
        Quote("If you really look closely, most overnight successes took a long time. ", "Steve Jobs"),
        Quote("The secret of success is to do the common thing uncommonly well.", "John D. Rockefeller Jr."),
        Quote("Don’t be afraid to give up the good to go for the great. ", "John D. Rockefeller"),
        Quote("Success is walking from failure to failure with no loss of enthusiasm. ", "Winston Churchill"),
        Quote("I owe my success to having listened respectfully to the very best advice, and then going away and doing the exact opposite. ", "G. K. Chesterton"),
        Quote("If you are not willing to risk the usual, you will have to settle for the ordinary. ", "Jim Rohn"),
        Quote("The ones who are crazy enough to think they can change the world, are the ones that do. ", "Anonymous"),
        Quote("All progress takes place outside the comfort zone. ", "Michael John Bobak"),
        Quote("It is kind of fun to do the impossible. ", "Walt Disney"),
        Quote("But I know, somehow, that only when it is dark enough can you see the stars.", "Martin Luther King, Jr"),
        Quote("I didn’t get there by wishing for it or hoping for it, but by working for it. ", "Estée Lauder"),
        Quote("The less their ability, the more their conceit. ", "Ahad Ha-am"),
        Quote("Live life to the fullest. ", "Anonymous"),
        Quote("Fall 7 times, stand up 8.", "Anonymous"),
        Quote("No one is you and that is your power. ", "Anonymous"),
        Quote("Sometimes the right path is not the easiest one. ", "Anonymous"),
        Quote("A mind troubled by doubt cannot focus on the course of victory.", "Arthur Golden"),
        Quote("Try not to become a man of success. Rather become a man of value. ", "Albert Einstein"),
        Quote("The way to get started is to quit talking and begin doing. ", "Walt Disney"),
        Quote("I find that the harder I work, the more luck I seem to have.", "Thomas Jefferson"),
        Quote("It is better to fail in originality than to succeed in imitation.", "Herman Melville"),
        Quote("The road to success and the road to failure are almost exactly the same.", "Colin R. Davis"),
        Quote("Don’t aim for success if you want it; just do what you love and believe in, and it will come naturally.", "David Frost"),
        Quote("Opportunities don’t happen. You create them.", "Chris Grosser"),
        Quote("Stop chasing the money and start chasing the passion.", "Tony Hsieh"),
        Quote("When you go through hardships and decide not to surrender, that is strength.", "Arnold Schwarzenegger"),
        Quote("There are better starters than me but I’m a strong finisher.", "Usain Bolt"),
        Quote("Tough times never last, but tough people do. ", "Robert H. Schuller"),
        Quote("I’ve failed over and over and over again in my life and that is why I succeed.", "Michael Jordan"),
        Quote("If you don’t get out of the box you’ve been raised in, you won’t understand how much bigger the world is. ", "Angelina Jolie"),
        Quote("Grind Hard, Shine Hard.", "Dwayne Johnson"),
        Quote("It hurt because it mattered. ", "John Green"),
        Quote("You will never know until you try. ", "Anonymous"),
        Quote("Every wall is a door. ", "Anonymous"),
        Quote("Behind the cloud is the sun still shining.", "Anonymous"),
        Quote("Do one thing every day that scares you.", "Anonymous"),
        Quote("The ones who are crazy enough to think they can change the world, are the ones that do. ", "Anonymous"),
        Quote("Better late than never.", "Anonymous"),
        Quote("We can give advice, but we cannot give conduct. ", "Anonymous"),
        Quote("Study the past if you would define the future. ", "Confucius"),
        Quote("Knowlegde is power and money. ", "Bill gates"),
        Quote("The secret of getting ahead is getting started. ", "Mark Twain"),
        Quote("It’s never too late.", "Anonymous"),
        Quote("Don’t aim for success if you want it; just do what you love and believe in, and it will come naturally. ", "David Frost"),
        Quote("Habit is second nature. ", "Michel de Montaigne"),
        Quote("Study without desire spoils the memory, and it retains nothing that it takes in.", "Leonardo da Vinci"),
        Quote("The merit of an action lies in finishing it to the end.", "Genghis Khan"),
        Quote("Education is what survives when what has been learned has been forgotten.", "B. F. Skinner"),
        Quote("Learning is not compulsory… neither is survival.", "W. Edwards Deming"),
        Quote("Seeing much, suffering much, and studying much, are the three pillars of learning. ", "Benjamin Disraeli"),
        Quote("Learning is not attained by chance, it must be sought for with ardor and attended to with diligence. ", "Abigail Adams"),
        Quote("What we have to do is to be forever curiously testing new opinions and courting new impressions.", "Walter Pater"),
        Quote("That is what learning is. You suddenly understand something you’ve understood all your life, but in a new way.", "Doris Lessing"),
        Quote("Isn’t it a pleasure to study, and to practice what you have learned?", "Confucius"),
        Quote("Courage is being scared to death… and saddling up anyway. ", "John Wayne"),
        Quote("I rise like the break of dawn.", "Anonymous"),
        Quote("Push yourself, because no one else is going to do for you. ", "Anonymous"),
        Quote("He that can have patience can have what he will. ", "Anonymous"),
        Quote("Yesterday you said tomorrow. Just do it.", "Anonymous"),
        Quote("If you eat all three meals, you’ll gain weight. ", "Sarang Kim"),
        Quote("You think you’re trying a new flavor, but it’s one you already know.", "Oak Joo Hyun"),
        Quote("You are not hungry. You are bored. Learn the differnce.", "Anonymous"),
        Quote("The reason I exercise is for the quality of life I enjoy.", "Anonymous"),
        Quote("When you feel like stopping , think about why you started.", "Anonymous"),
        Quote("Reading is to the mind as what exercise is to the body.", "Anonymous"),
        Quote("Life begins at the end of your comfort zone.", "Anonymous"),
        Quote("The only bad workout is the one that didn’t happen.", "Anonymous"),
        Quote("To change your body you must first change your mind.", "Anonymous"),
        Quote("Confidence will make you happier than any diet will.", "Anonymous"),
        Quote("Better a broken diet than no diet that at all.", "Anonymous"),
        Quote("Time for action.", "Anonymous"),
        Quote("It’s never too late.", "Anonymous"),
        Quote("A little progress each day adds up to big results.", "Anonymous"),
        Quote("Nothing taste as good as skinny feels.", "Anonymous"),
        Quote("The pain from being over weight outlasts the pain of exercise.", "Anonymous"),
        Quote("It’s never too late to change old habits.", "Anonymous"),
        Quote("Slow and steady wins the race.", "Anonymous"),
        Quote("Change your mind change your body.", "Anonymous"),
        Quote("Winners find a way. losers find an excuse.", "Anonymous"),
        Quote("Life is divided into fat and not fat.", "Lee sora")
    )
}